name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: present
      run: pwd
    - name: list
      run: ls -al
    - name: configure
      run: cd src
    - name: make
      run: cmake
    - name: install
      run: cmake install
    - name: make distcheck
      run: make distcheck
